apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginxapp

spec:
  replicas: 1 
  selector:
    matchLabels:
      app: nginx

  template:
    metadata:
      name: nginx-pod
      labels:
        app: nginxapp

    spec:
      containers:
        - name: nginx-container 
          image: babaknasrolahy/nginxapp:latest
          ports:
           - containerPort: 80
      resources:
        limits:
          cpu: 100m
        requests:
          cpu: 50m
        
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service

spec:
  type: LoadBalancer
  selector:
    app: nginxapp
  
  ports:
   - protocol: TCP
     port: 80
     targetPort: 80
     nodePort: 30000
